### ISSUE TITLE
Fixed version

### ISSUE THREAD

**Issue by samo79** [walkero-gr/mediavault#5]
Current version report:

1.0.0 (30.4.2021)

Maybe extend it fully as:

MediaVault 1.0.0 (30.4.2021)

**Comment by walkero-gr** [comment]
Will consider that. Does it help you on something specific, i.e. do you use those version strings on any script?

**Comment by samo79** [comment]
Not yet, just usually the program name is always included in the version string along with its version number :-)

**Comment by walkero-gr** [comment]
@samo79 It took me some time :D but this is fixed on the latest v1.3.0 release.
