### ISSUE TITLE
Selecting about in the menu, and get a busy mouse pointer.

### ISSUE THREAD

**Issue by khval** [walkero-gr/mediavault#8]
Selecting about in the menu, and get a busy mouse pointer.

**Comment by walkero-gr** [comment]
@khval I guess you get a busy pointer on the main Window, right? If so, this is the way it works, it is not a bug but a feature 😄 
If not, please tell me if it blocks the about window and you can't close it or scroll the text.

**Comment by khval** [comment]
Works now, first time did not see any about window.

**Comment by walkero-gr** [comment]
Thanks for the clarification.
